version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: life_pm
    volumes:
      - ./volumes/todo_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio
    container_name: minio1
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ./volumes/minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: spring-boot-app
    restart: unless-stopped
    depends_on:
      - postgres
      - minio
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      # Hibernate & JPA
      SPRING_JPA_DATABASE_PLATFORM: ${SPRING_JPA_DATABASE_PLATFORM}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}

      # JWT Security
      SECURITY_JWT_SECRET_KEY: ${SECURITY_JWT_SECRET_KEY}
      SECURITY_JWT_ACCESS_TOKEN_EXPIRATION_SEC: ${SECURITY_JWT_ACCESS_TOKEN_EXPIRATION_SEC}
      SECURITY_JWT_REFRESH_TOKEN_EXPIRATION_SEC: ${SECURITY_JWT_REFRESH_TOKEN_EXPIRATION_SEC}

      # File Storage
      FILES_ROOT_LOCATION: ${FILES_ROOT_LOCATION}

      # MinIO Configuration
      MINIO_URL: ${MINIO_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET_ATTACHMENTS: ${MINIO_BUCKET_ATTACHMENTS}
    ports:
      - "8081:8081"
    volumes:
      - ./storage:/app/storage
